### ISSUE TITLE
type error: property undefined

### ISSUE THREAD

**Issue by alkavishwa09** [intercom/intercom-node#206]
node dev/test.js
C:\blockchain\dev\blockchain.js:78
        if (currentBlock['previousBlockHash'] !== previousBlock['hash']) validChain = false;
                        ^

TypeError: Cannot read property 'previousBlockHash' of undefined
    at Blockchain.chainIsValid (C:\blockchain\dev\blockchain.js:78:25)
    at Object.<anonymous> (C:\blockchain\dev\test.js:116:32)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3) 2. 
 3.

**Comment by choran** [comment]
Hi @alkavishwa09 
Unfortunately, I am not sure what issue you are referring to here?
To ensure we fully understand the issue you are raising can you please provide more context along with the error you are seeing and clarification of what you expect to occur and what actually occurred.

I will close this for now but please feel free to reopen if you have more context.
