### ISSUE TITLE
Creating user with same email works twice and fails on third attempt.

### ISSUE THREAD

**Issue by omarsafwany** [intercom/intercom-node#266]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-node version: 2.11.0
  - Node version: 12.4.0

## Expected behavior
I should be able to create a user even with same email address. Maybe if email matches, it can update it with new attributes accordingly.

## Actual behavior
The first two times work perfectly and two users (with the same email address) are created. Any subsequent attempts fail.

## Steps to reproduce
 1. Create user using `intercom.contacts.create` with a certain email. success
 2. Create another user but with same email as the previous one. success
 3. Third attempt. fail

## Logs
```
Error: Multiple existing users match this email address adevelopment@notify.com - must be more specific using user_id
    at callback (/home/node/app/node_modules/intercom-client/dist/client.js:227:17)
    at Request._callback (/home/node/app/node_modules/intercom-client/dist/client.js:133:13)
    at Request.self.callback (/home/node/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at Request.<anonymous> (/home/node/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at IncomingMessage.<anonymous> (/home/node/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at IncomingMessage.EventEmitter.emit (domain.js:471:20)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
From previous event:
    at Client.promiseProxy (/home/node/app/node_modules/intercom-client/dist/client.js:123:16)
    at Client.post (/home/node/app/node_modules/intercom-client/dist/client.js:163:19)
    at Contact.create (/home/node/app/node_modules/intercom-client/dist/contact.js:40:26)
    at /home/node/app/src/Routes/accounts.js:238:42
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  statusCode: 409,
  body: {
    type: 'error.list',
    request_id: '0010tbp1k95ecd2f673g',
    errors: [ [Object] ]
  },
  headers: {
    date: 'Sun, 03 May 2020 05:44:48 GMT',
    'content-type': 'application/json; charset=utf-8',
    'transfer-encoding': 'chunked',
    connection: 'close',
    status: '409 Conflict',
    'cache-control': 'no-cache',
    'x-ratelimit-limit': '167',
    'x-ratelimit-reset': '1588484690',
    'strict-transport-security': 'max-age=31556952; includeSubDomains; preload',
    'x-ratelimit-remaining': '167',
    'x-intercom-version': '6646965305f9544e3892313545160aca953b0253',
    vary: 'Accept-Encoding',
    'x-xss-protection': '1; mode=block',
    'x-request-id': '0010tbp1k95ecd2f673g',
    'intercom-version': '2.0',
    'x-runtime': '0.060249',
    'x-frame-options': 'SAMEORIGIN',
    'x-content-type-options': 'nosniff',
    'set-cookie': [
      '_mkra_ctxt=21a0984bf1c19db36fe849881431ed33--409; ' +
        'path=/; max-age=5; HttpOnly; secure'
    ],
    server: 'nginx'
  }
}
```

The error mentions to use `user_id` which I do but cannot find it in the response/dashboard.

**Comment by lloydliyu** [comment]
Hey @omarsafwany :wave:

This looks like the issue is occurring with the API itself and not the SDK. If you are still having issues with this, and you haven't already, I'd recommend reaching out to the support team using the Messenger on https://intercom.com

Closing this as it is not an issue with the SDK itself.
