### ISSUE TITLE
Closing a conversation results in a BadResponse from Intercom

### ISSUE THREAD

**Issue by ardelio** [intercom/intercom-node#309]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info

-   intercom-node version: 3.1.1
-   Node version: 16.13.2

## Expected behavior

Able to close a conversation

## Actual behavior

BadResponse API Error is thrown

## Steps to reproduce

1. `await client.conversations.close({ id: conversationId, adminId: adminId, body: 'closing' })`
2. 🔥 

## Logs

```
yarn run v1.22.10
$ . .env && node src/index.js
/Users/anthonysceresini/code/propeller/intercom-integration-prototype/node_modules/intercom-client/dist/errors/badResponse.error.js:8
        var _this = _super.call(this, message) || this;
                           ^

Error: Type isn't an option
    at new BadResponseError (/Users/anthonysceresini/code/propeller/intercom-integration-prototype/node_modules/intercom-client/dist/errors/badResponse.error.js:8:28)
    at Client.checkOnErrorInResponse (/Users/anthonysceresini/code/propeller/intercom-integration-prototype/node_modules/intercom-client/dist/client.js:232:16)
    at Client.<anonymous> (/Users/anthonysceresini/code/propeller/intercom-integration-prototype/node_modules/intercom-client/dist/client.js:142:36)
    at step (/Users/anthonysceresini/code/propeller/intercom-integration-prototype/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/Users/anthonysceresini/code/propeller/intercom-integration-prototype/node_modules/tslib/tslib.js:124:57)
    at rejected (/Users/anthonysceresini/code/propeller/intercom-integration-prototype/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  body: {
    type: 'error.list',
    request_id: '000bqse8qr9ur7vlk580',
    errors: [ { code: 'parameter_invalid', message: "Type isn't an option" } ]
  },
  headers: {
    date: 'Wed, 09 Feb 2022 22:52:08 GMT',
    'content-type': 'application/json; charset=utf-8',
    'transfer-encoding': 'chunked',
    connection: 'close',
    status: '400 Bad Request',
    'cache-control': 'no-cache',
    'x-ratelimit-limit': '167',
    'x-ratelimit-reset': '1644447133',
    'strict-transport-security': 'max-age=31556952; includeSubDomains; preload',
    'x-ratelimit-remaining': '165',
    vary: 'Accept,Accept-Encoding',
    'x-intercom-version': 'cbd3c99de4c1acf7cc4d516d7d7ea7042f33748d',
    'x-xss-protection': '1; mode=block',
    'x-request-id': '000bqse8qr9ur7vlk580',
    'intercom-version': '2.4',
    'x-runtime': '0.091323',
    'x-frame-options': 'SAMEORIGIN',
    'x-content-type-options': 'nosniff',
    server: 'nginx'
  },
  statusCode: 400
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ardelio** [comment]
Thank you @hypeofpipe 🙇
