### ISSUE TITLE
usePromise throws error on list

### ISSUE THREAD

**Issue by kmiyashiro** [intercom/intercom-node#75]
intercom-node 2.6
node 5.5

I am trying to fetch a list of my conversations, but when I use `usePromises` it throws an error. If I use it with callbacks, it works as expected.

*Update*: Turns out you need to pass an empty object instead of undefined if you want to fetch all. I would add this to the docs or default the query to `{}` if null/undefined.

```js
const Intercom = require('intercom-client');
const INTERCOM_API_KEY = process.env.INTERCOM_PRODUCTION_RO_API_KEY;
const INTERCOM_APP_ID = process.env.INTERCOM_PRODUCTION_APP_ID;

const client = new Intercom.Client(INTERCOM_APP_ID, INTERCOM_API_KEY)
  .usePromises();

client.conversations.list()
  .then((res) => {
    console.log(res);
  });
```

```
kel@Wombat:~/Projects/intercom-explorer (master #)$ node index.js
/Users/kel/Projects/intercom-explorer/node_modules/unirest/index.js:214
        if (!value.length) return $this;
                  ^

TypeError: Cannot read property 'length' of undefined
    at Object.$this.query (/Users/kel/Projects/intercom-explorer/node_modules/unirest/index.js:214:19)
    at Client.get (/Users/kel/Projects/intercom-explorer/node_modules/intercom-client/dist/client.js:155:144)
    at Conversation.list (/Users/kel/Projects/intercom-explorer/node_modules/intercom-client/dist/conversation.js:21:26)
    at Object.<anonymous> (/Users/kel/Projects/intercom-explorer/index.js:8:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

**Comment by hellsan631** [comment]
```
client.conversations.list()
```

you need to send in an empty object

```
client.conversations.list({})
```

should work

**Comment by kmiyashiro** [comment]
@hellsan631 thanks, I actually figured it out in my update :smile:. I'm keeping this issue here since I recommended either putting this in the docs or default it to `{}` if nothing is passed. At the very least, a helpful error should throw.

**Comment by RuairiK** [comment]
Thanks for the update, we'll look at adding this to our docs.

**Comment by hellsan631** [comment]
This should perhaps be changed:

```js
 list(data, f) {
    return this.client.get('/conversations', data, f);
  }
```

into (or something like that)

```js
list(data, f) {
  return this.client.get('/conversations', data || {}, f);
}
```
